====================================
The ``101-lazy_matrix_mul`` module
====================================

Test for the ``lazy_matrix_mul`` function which uses numpy
==========================================================

Import function from module:
	>>> lazy_matrix_mul = __import__("101-lazy_matrix_mul").lazy_matrix_mul


Testing with only integers:
	>>> print(lazy_matrix_mul([[1, 2, 4], [4, 34, 5]], [[24, 5, 2], [3, 4, 5], [1, 2, 3]]))
	[[ 34  21  24]
	 [203 166 193]]

	>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]]))
	[[ 7 10]
	 [15 22]]

	>>> print(lazy_matrix_mul([[1, 2], [3, 4], [5, 6]], [[7, 8, 9], [10, 11, 12]]))
	[[ 27  30  33]
	 [ 61  68  75]
	 [ 95 106 117]]


Testing integers or float args:
	>>> print(lazy_matrix_mul([[1.5, 2.5], [3.5, 4.5]], [[5.5, 6.5], [7.5, 8.5]]))
	[[27. 31.]
	 [53. 61.]]
	

Teting with incorrect number of rows or/and columns:
	>>> print(lazy_matrix_mul([[1, 2, 3], [4, 5, 6]], [[7, 8], [9, 10]]))
	Traceback (most recent call last):
	...
	ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)


Testing an empty list in the list:
	>>> print(lazy_matrix_mul([[1, 2], [3, 4]], []))
	Traceback (most recent call last):
	...
	ValueError: shapes (2,2) and (0,) not aligned: 2 (dim 1) != 0 (dim 0))

	>>> print(lazy_matrix_mul([[], []], [[5, 6], [7, 8]]))
	Traceback (most recent call last):
	...
	ValueError: shapes (2,0) and (2,2) not aligned: 0 (dim 1) != 2 (dim 0)

Excetptions:
	>>> print(lazy_matrix_mul([[1, 2], [3, 'a']], [[5, 6], [7, 8]]))
	Traceback (most recent call last):
	...
	TypeError: invalid data type for einsum

	>>> print(lazy_matrix_mul([[1, 2], 23, 45], [[5, 6], [7, 8]]))
	Traceback (most recent call last):
	...
	ValueError: setting an array element with a sequence.

	>>> print(lazy_matrix_mul([[1, 2], [23, 45]], [5, 6, [7, 8]]))
	Traceback (most recent call last):
	...
	ValueError: setting an array element with a sequence.


None:
	>>> print(lazy_matrix_mul(None, [[5, 6], [7, 8]]))
	Traceback (most recent call last):
	...
	TypeError: Object arrays are not currently supported

	>>> print(lazy_matrix_mul([[1, 2], [3, 4]], None))
	Traceback (most recent call last):
	...
	TypeError: Object arrays are not currently supported

	>>> print(lazy_matrix_mul([[None]], [[5, 6], [7, 8]]))
	Traceback (most recent call last):
	...
	TypeError: Object arrays are not currently supported

	>>> print(lazy_matrix_mul([[1, 2], [3, 4]], [[None, 8], [5, 6]]))
	Traceback (most recent call last):
	...
	TypeError: Object arrays are not currently supported

	>>> print(lazy_matrix_mul(None, None))
	Traceback (most recent call last):
	...
	Object arrays are not currently supported
	
	
	>>> ma = [[1, 2, 3], [3, 4, 5]]
	>>> mb = [[1, 2], [3, 4]]
	>>> print(lazy_matrix_mul(ma, mb))
	Traceback (most recent call last):
	...	
	ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

	
	
